/**
 * Program errors by name, and the signer's own refusal type.
 *
 * The api's "build it again" fix strings are ignored on purpose: a curator
 * that retries on a string it did not understand is a curator that loops.
 * Instead every program error is named from the enum order of the source
 * (`programs/portfolio_factory/src/errors.rs`, `stoken/src/errors.rs`),
 * so `RebalanceTooSoon` and `PoolPricePending` reach the journal, the alert
 * and the LLM as words with a documented action (skills ERRORS.md).
 *
 * The tables are embedded (`program-errors.generated.js`, regenerated by
 * `scripts/generate-program-errors.mjs`) because the signer's container has
 * no sibling checkout; `test/errors.test.js` re-parses the `.rs` files when
 * a checkout is present so a drifted table fails a test rather than
 * mislabelling a refusal in production.
 */
import { FACTORY_ERRORS, STOKEN_ERRORS } from './program-errors.generated.js';

export { FACTORY_ERRORS, STOKEN_ERRORS };

/** Anchor numbers `#[error_code]` variants from here, in declaration order. */
export const ANCHOR_CUSTOM_ERROR_BASE = 6000;

const TABLES = Object.freeze({
  portfolio_factory: FACTORY_ERRORS,
  stoken: STOKEN_ERRORS,
});

/**
 * Program ids this process knows, for attributing a bare numeric code to the
 * program whose id appears in the same text ("Program CB1T… failed: custom
 * program error: 0x1772"). Read from the manifest through the chain package
 * when it is importable; otherwise attribution comes only from the caller's
 * `program` hint or from an unambiguous error name.
 */
let knownProgramIds = null;
async function defaultProgramIds() {
  if (knownProgramIds) return knownProgramIds;
  const ids = new Map();
  try {
    const chain = await import('@composable-portfolios/chain');
    for (const name of Object.keys(TABLES)) {
      try {
        ids.set(chain.programId(name).toBase58(), name);
      } catch {
        // not pinned on this deployment
      }
    }
  } catch {
    // chain package unavailable: attribution falls back to hints and names
  }
  knownProgramIds = ids;
  return ids;
}

/** Warm the manifest-derived program-id map (index.js calls this once at boot). */
export async function loadKnownProgramIds() {
  return defaultProgramIds();
}

const PATTERNS = Object.freeze({
  hex: /custom program error:\s*0x([0-9a-f]+)/i,
  number: /Error Number:\s*(\d+)/i,
  customJson: /"Custom"\s*:\s*(\d+)/,
  name: /Error Code:\s*([A-Z][A-Za-z0-9]*)/,
});

function programsNaming(name) {
  return Object.entries(TABLES)
    .filter(([, table]) => table.includes(name))
    .map(([program]) => program);
}

/**
 * Name a program error out of any text: a simulation log, a send message,
 * an api `error.message`. Understands "custom program error: 0x1772",
 * "Error Number: 6002", `{"Custom":6002}` and "Error Code: RebalanceTooSoon".
 *
 * Both programs number their enums from 6000, so a bare number is ambiguous
 * between them. Attribution, in order: the caller's `program` hint (the verb
 * knows which program it called), a known program id in the text, an error
 * name that exists in exactly one table, and a name-plus-number pair that
 * fits exactly one table. When none applies the result says `program:
 * 'unknown'`, `name: null` and lists the `candidates` per program — the
 * journal records what is known rather than guessing.
 *
 * @param {string} text
 * @param {{ program?: 'portfolio_factory' | 'stoken', programIds?: Map<string, string> | Record<string, string> }} [hints]
 *   `programIds` maps base58 → program name; when omitted the manifest's pins are used once they have been loaded.
 * @returns {{ code: number, name: string | null, program: 'portfolio_factory' | 'stoken' | 'unknown', candidates?: Record<string, string> } | null}
 */
export function nameProgramError(text, hints = {}) {
  const source = String(text ?? '');
  if (source === '') return null;

  const hex = PATTERNS.hex.exec(source);
  const number = PATTERNS.number.exec(source);
  const custom = PATTERNS.customJson.exec(source);
  const named = PATTERNS.name.exec(source);

  let code = null;
  if (hex) code = Number.parseInt(hex[1], 16);
  else if (number) code = Number.parseInt(number[1], 10);
  else if (custom) code = Number.parseInt(custom[1], 10);
  const name = named ? named[1] : null;
  if (code === null && name === null) return null;

  const idMap = hints.programIds instanceof Map
    ? hints.programIds
    : new Map(Object.entries(hints.programIds ?? {}));
  for (const [id, program] of knownProgramIds ?? []) {
    if (!idMap.has(id)) idMap.set(id, program);
  }

  let program = null;
  if (hints.program && TABLES[hints.program]) {
    program = hints.program;
  } else {
    for (const [id, candidate] of idMap) {
      if (TABLES[candidate] && source.includes(id)) {
        program = candidate;
        break;
      }
    }
  }
  if (!program && name) {
    const owners = programsNaming(name);
    if (owners.length === 1) [program] = owners;
    else if (owners.length > 1 && code !== null) {
      const fits = owners.filter((owner) => TABLES[owner][code - ANCHOR_CUSTOM_ERROR_BASE] === name);
      if (fits.length === 1) [program] = fits;
    }
  }

  if (program) {
    const table = TABLES[program];
    const index = code === null ? table.indexOf(name) : code - ANCHOR_CUSTOM_ERROR_BASE;
    const resolvedName = index >= 0 && index < table.length ? table[index] : null;
    return {
      code: code ?? (index >= 0 ? ANCHOR_CUSTOM_ERROR_BASE + index : null),
      // The number wins over a name that disagrees with it: the number is
      // what the runtime returned, the name is what a log line claimed.
      name: resolvedName ?? name,
      program,
    };
  }

  const candidates = {};
  if (code !== null && code >= ANCHOR_CUSTOM_ERROR_BASE) {
    for (const [owner, table] of Object.entries(TABLES)) {
      const candidate = table[code - ANCHOR_CUSTOM_ERROR_BASE];
      if (candidate) candidates[owner] = candidate;
    }
  }
  return { code, name: name ?? null, program: 'unknown', candidates };
}

/** HTTP status per refusal code (README §2 Errors); anything unlisted is 422. */
export const REFUSAL_STATUS = Object.freeze({
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  OPS_ONLY: 403,
  VERB_DENIED: 403,
  WITHDRAW_CRON_BLOCKED: 403,
  PORTFOLIO_NOT_ALLOWED: 403,
  NOT_FOUND: 404,
  TARGETS_PENDING: 409,
  SELF_LOCKED: 409,
  PAUSED: 409,
  NO_PENDING_CHANGE: 409,
  APPLY_IN_FLIGHT: 409,
  VAULT_PAUSED: 409,
  RATE_LIMITED: 429,
  PROPOSAL_QUOTA: 429,
  DEPOSIT_DAILY_CAP: 429,
  WITHDRAW_DAILY_CAP: 429,
  UPSTREAM: 502,
  BUILD_REFUSED: 502,
  SEND_FAILED: 502,
  NOT_A_TRANSACTION: 502,
  WRONG_PAYER: 502,
  FOREIGN_PROGRAM: 502,
  FOREIGN_LOOKUP_TABLE: 502,
  UNKNOWN_INSTRUCTION: 502,
  UNEXPECTED_INSTRUCTIONS: 502,
  WRONG_PORTFOLIO: 502,
  WRONG_ACCOUNT: 502,
  TARGETS_MISMATCH: 502,
  UNEXPECTED_STEP: 502,
  LOW_SOL: 503,
  INVARIANT_DRIFT: 503,
  BOOK_NOT_FRESH: 503,
  // Added after the round-1 review: codes the modules raise that had fallen to the 422 default.
  WHY_REQUIRED: 400,
  CAP_HEADROOM: 422,
  INSUFFICIENT_SHARES: 422,
  PAGED_PROPOSE_UNSUPPORTED: 502,
  MISSING_CUSTODY: 503,
  INVARIANTS_UNVERIFIED: 503,
});

/** A refusal: `code` is the contract, `status` follows REFUSAL_STATUS, `detail` is optional data (never a secret). */
export class Refusal extends Error {
  constructor(code, message, detail) {
    super(message);
    this.name = 'Refusal';
    this.code = code;
    this.status = REFUSAL_STATUS[code] ?? 422;
    if (detail !== undefined) this.detail = detail;
  }
}
